<div class="toc">
	<h3>GENERAL CONDITIONS for PROVISION of GOODS and SERVICES</h3>
	
	<ol>
		<li><b>GENERAL:</b> In these General Conditions Malley Industries Inc. is referred to as the "Contractor" and the party named on the attached quotation is referred to as the "Customer". Acceptance of the quotation by the Customer or the commencement of any work by the Contractor shall constitute acceptance of these General Conditions which shall apply to and govern all goods and services provided by the Contractor, including extras and additional work subsequently ordered (the "Goods" and "Services"). The quotation, these General Conditions and all other documents referenced therein and herein shall be hereinafter referred to as the "Contract".</li>
		<li><b>CHANGES:</b> No change shall be made to the Contract, including the workscope, without the prior written consent of the Contractor. Any such change shall constitute an extra charge to the Contract.</li>
		<li><b>OVERTIME:</b> Unless provided otherwise in the Contract, if the Customer requests that the Contractor's employees work overtime, the extra cost of such overtime may be an additional charge to the Contract and shall be paid by the Customer.</li>
		<li><b>PAYMENT:</b> Unless otherwise provided, all invoices shall become due and payable before any vehicle leaves the Contractor’s plant and within thirty (30) days of receipt for all products and services pending credit approval. Interest will be charged on overdue accounts at the rate of two percent (2%) per month.</li>
		<li><b>TAXES:</b> Unless stated otherwise in the Contract, all taxes, including HST, are not included in the price and, if applicable, will be paid by the Customer.
		<li><b>WARRANTY:</b>
			<ol style="list-style-type: lower-alpha;">
				<li>Warranties are effective after performance of the Services, and that the services will be free from any defect, error or omission (collectively referred to herein as "Defect"). The liability and obligation of the Contractor to the Customer in respect of any Defect in the Services shall be limited, at the Contractor’s option, to the correction of the Defect or the reperformance of the Services.</li>
				<li>The Contractor does not warrant or provide any other type of representation with respect to the Goods provided under the Contract. Customer's sole warranty with respect to the Goods, if any, is that provided by the manufacturer of the Goods.</li>
				<li>The warranties, obligations and liabilities of the Contractor and remedies of the Customer set forth in this paragraph 6 are exclusive and in substitution for, and the Customer hereby waives, releases and renounces, all other warranties, obligations and liabilities of the Contractor, express or implied, arising by law or otherwise, with respect to breach of warranty contained in this paragraph 6, including but not limited to the following rights and obligations: (i) any obligation, liability, right, claim or remedy in tort, whether or not arising from the negligence of the Contractor or otherwise; (ii) any obligation, liability, right, claim or remedy for loss of or damage to property or for personal injury (including death), whether suffered or incurred by the Customer or any third party, or for any other direct, indirect, incidental or consequential damage; and (iii) any implied warranty of merchantability or fitness for a particular purpose.</li>
			</ol>
		</li>
		<li><b>DEFAULT:</b> If the Customer defaults under the Contract by failing to make payments as required or commits any other breach of contract, the Contractor may, without notice and without prejudice to any other  right it may have under the Contract, at common law or otherwise, suspend performance of the contract and/or terminate the whole or any part of the Contract. In such case the Customer shall be responsible to pay to the Contractor any and all costs, expenses, fees for service or otherwize as incured by the Contractor relative to the performance, in whole or in part, of the contract.</li>
		<li><b>INDEMNITY:</b> The Customer shall indemnify and hold the Contractor harmless from and against any and all claims, demands, causes of action, loss, cost, damage and expense arising out of or in connection with the performance or non-performance of the Services or the provision of the Goods ("Claims") including, without limitation, Claims arising from injuries (including death) to any person (including employees of the Contractor and the Customer) and loss of or damage to property, in any way sustained, or alleged to have been sustained, in connection with or arising out of the performance or non-performance of the Services or the provision of the Goods by the Contractor, its agents, employees or subcontractors.</li>
		<li><b>FORCE MAJEURE:</b> If the performance of any part of the Contract is prevented, hindered or delayed by reason or any cause or causes beyond the reasonable control of the Contractor, the Contractor shall be excused from such performance to the extent that it is necessarily prevented, hindered or delayed thereby during the continuance of any such happening or event, and the Contract shall be deemed suspended as long as and to the extent that any such cause prevents or delays its performance.</li>
		<li><b>LIMITATION OF LIABILITY:</b> Notwithstanding any other provision of the Contract, the Contractor shall not be liable to the Customer for any special, indirect, incidental or consequential damage. The Customer waives, releases and renounces any and all right to make a claim against the Contractor in tort, including negligence. In no event will the Contractor’s liability arising from any default or non-performance under the Contract exceed the Contract price.</li>
		<li><b>TITLE:</b> Title to the Goods and risk of loss thereof shall pass to the Customer upon delivery by Contractor.</li>
		<li><b>WAIVER:</b> The failure to exercise any right or the waiver of a breach of any provision of the Contract shall not be deemed a waiver of any subsequent breach of such provision or of any other provision.</li>
		<li><b>PRIORITY:</b> In the event of conflict or inconsistency between different parts of the Contract, the order of priority will be as follows: (1) provisions set out in the quotation; (2) these General Conditions; and (3) other contract documents, if any.</li>
		<li><b>ASSIGNMENT:</b> The Contract shall not be assigned by the Customer without the prior written consent of the Contractor.</li>
		<li><b>SUCCESSORS AND ASSIGNS:</b> The Contract shall enure to the benefit of, and is binding upon, the parties hereto, their successors and permitted assigns.</li>
		<li><b>GOVERNING LAW:</b> The Contract shall be interpreted, construed, governed by, and the relations between the parties are to be determined in accordance with the laws in force in the Province of New Brunswick and the parties agree to submit to the exclusive jurisdiction of the Courts of such province.</li>
		<li><b>ENTIRE AGREEMENT:</b> The Contract shall constitute the entire agreement between the parties with respect to the subject matter hereof and supercedes all previous communications, representations or understandings, whether oral or written.</li>

	</ol>
</div>